### ISSUE TITLE
How to get an eclipse-based dependency (p2 or mavenCentral)?

### ISSUE THREAD

**Issue by frankbenoit** [diffplug/goomph#108]
Hi Ned,

I find it difficult to understand how to use Goomph.

Creating a project using SWT/JFace seems to work:
````
eclipseMavenCentral {
    release '4.13.0', {
        implementation 'org.eclipse.swt'
        implementation 'org.eclipse.jface'
        useNativesForRunningPlatform()
    }
}
````

Next I want to use SWTBot, from the update site https://download.eclipse.org/technology/swtbot/releases/latest/
  - 'org.eclipse.swtbot.go'
  - 'org.eclipse.swtbot.junit4_x'
  - 'org.eclipse.swtbot.swt.finder'
 
How can i make those bundles available?

Frank

**Comment by nedtwigg** [comment]
> I find it difficult to understand how to use Goomph.

Sorry :(  Ignoring the "IDE-generation" part, and focusing on just on the "build an eclipse-based application" part, here is a high-level overview:

# Algorithm for finding eclipse-based dependencies

A lot of eclipse projects only publish to their own p2 repository.  Some publish to both p2 and mavenCentral.

- Search for your library here: https://search.maven.org/
- If it shows up, you can get it directly from mavenCentral if you want
    - If the groupId is one of [these](https://github.com/diffplug/goomph/blob/4ac5b997f805b020b80d1d5db092238ec8833f82/src/main/java/com/diffplug/gradle/eclipse/MavenCentralMapping.java#L45-L47), then you can use our `eclipseMavenCentral` to specify the version in terms of the eclipse release (e.g. `4.7.2`) rather than the long per-jar naming format that most eclipse projects use
- if it doesn't show up, then you have no choice but to use `p2asmaven`. 

# Details

## Consuming p2 dependencies

We built Goomph because we found it difficult to use p2.  So we wrapped up p2 with `p2asmaven`, which makes it possible to run the `p2` standalone application and stuff the results into a plain-old maven repository.  This will always work with any `p2` repository, but it's just a wrapper.  That means that there are a lot of performance and "debuggability" problems that we can't solve.  For example, when a `p2` mirror operation hangs, the answer lies deep inside `p2` internals - we're just shelling out to it, not much we can do.

## Cross-published p2 / mavenCentral dependencies

Starting with eclipse `4.6.2`, when eclipse published a new release to their official p2 repository, they also published to `mavenCentral`.  However, this is only for the "core" libraries - SWT, OSGi/Equinox, JDT, PDE.  The `eclipseMavenCentral` plugin just lets you download those dependencies using `4.7.0` as your version, rather than the long unique-to-each jar version that they have in maven central.  SWTBot is not part of this core, so you can't use `eclipseMavenCentral` to do it.

## Building RCP applications

We used to ship DiffPlug as an OSGi/RCP application.  We opensourced the code that we used to do this as `PdeBuildTask`/`PdeAntTask`.  Over time, we found that OSGi/RCP were adding more maintenance burden than they were worth, and we have stopped using them.  So they still work for older eclipse versions, and I don't know why they wouldn't work for newer eclipse versions too.  We're happy to take PRs to update them, and its fine to post bugs documenting bugs without a solution, but nobody at DiffPlug is actively working on this.

**Comment by frankbenoit** [comment]
Hi Ned,

thanks for you reply.

I don't yet understand how I can explore the available APIs. Perhaps this is a general problem for me understanding Gradle plugins.
Now i _guessed_, perhaps it takes `repo`, and really that worked. 
But how am I able to find this in the docs? As Groovy/Eclipse gives my no hints via autocomplete proposals, i am fully depending on the written docs.

````
p2AsMaven {
    group 'org.eclipse.swtbot', {
        repo 'http://download.eclipse.org/technology/swtbot/releases/latest'
        iu 'org.eclipse.swtbot.go'
        iu 'org.eclipse.swtbot.junit4_x'
        iu 'org.eclipse.swtbot.swt.finder'
    }
}
eclipseMavenCentral {
    release '4.13.0', {
        implementation 'org.eclipse.swt'
        implementation 'org.eclipse.jface'
        useNativesForRunningPlatform()
    }
}
````

Now i see it accessing the repos, but failing to resolve:
````
[p2.mirror] Problems resolving provisioning plan.
[p2.mirror] Unable to satisfy dependency from org.eclipse.swtbot.junit4_x 2.8.0.201906121535 to package org.eclipse.swt.widgets 0.0.0.
[p2.mirror] Unable to satisfy dependency from org.eclipse.swtbot.junit4_x 2.8.0.201906121535 to package org.junit 4.12.0.
[p2.mirror] Unable to satisfy dependency from org.eclipse.swtbot.junit4_x 2.8.0.201906121535 to package org.junit.runner 4.12.0.
...
````

How can i make p2AsMaven aware: 
`package org.junit.runner 4.12.0` shall be found in `junit:junit:4.12` ?
`package org.eclipse.swt.widgets 0.0.0` shall be found in `???:org.eclipse.swt` ?

Frank

**Comment by hacki11** [comment]
Just found out about this plugin. Did i understand the following correctly:
It is not possible to make PdeBuildTask aware of that the base directory for the target (p2) is handled by eclipseMavenCentral instead of p2AsMaven?

Do i have to mirror the p2 repository and have the eclipseMavenCentral redundantly?

**Comment by nedtwigg** [comment]
> I don't yet understand how I can explore the available APIs.

The README has (broken) links to the javadoc, but changing `3.18.1` to `3.18.0` in the URL will fix them.  The broken links will get fixed the next time I work on goomph (next eclipse release).  In the meantime:

https://diffplug.github.io/goomph/javadoc/3.18.0/com/diffplug/gradle/p2/AsMavenPlugin.html

> How can i make p2AsMaven aware

You'll have to get `p2` to ignore missing dependencies.  We're just shelling out to [this](https://wiki.eclipse.org/Equinox/p2/Ant_Tasks#SlicingOptions), so setting `followStrict, true` in the [slicing options](https://diffplug.github.io/goomph/javadoc/3.18.0/com/diffplug/gradle/p2/AsMavenPlugin.html#slicing-options) should work.

p2AsMaven [doesn't encode p2 dependencies into maven dependencies](https://github.com/diffplug/goomph/issues/5), so there won't be any problem that the p2 groupId is different than the maven groupId.

@hacki11 please open a new issue if you want to discuss further, but probably you should not use `eclipseMavenCentral` if you also want to use `PdeBuildTask`.

**Comment by frankbenoit** [comment]
Hi

sorry for again asking....
Now I have this:
````
buildscript {
	repositories {
		jcenter()
		mavenCentral()
	}
	dependencies {
		classpath 'com.diffplug.gradle:goomph:3.18.1'
	}
} 

apply plugin: 'com.diffplug.gradle.eclipse.mavencentral'
apply plugin: 'com.diffplug.gradle.p2.asmaven'
apply plugin: 'java'

repositories {
    jcenter()
	mavenCentral()
}

p2AsMaven {
    group 'org.eclipse.swtbot', {
        repo 'http://download.eclipse.org/technology/swtbot/releases/latest'
        iu 'org.eclipse.swtbot.go'
        iu 'org.eclipse.swtbot.junit4_x'
        iu 'org.eclipse.swtbot.swt.finder'
        slicingOption 'followStrict', 'true'
    }
}

eclipseMavenCentral {
    release '4.13.0', {
        implementation 'org.eclipse.swt'
        implementation 'org.eclipse.jface'
        useNativesForRunningPlatform()
    }
}

dependencies {
    implementation 'org.eclipse.swtbot:org.eclipse.swtbot.go'
    implementation 'org.eclipse.swtbot:org.eclipse.swtbot.junit4_x:+'
    implementation 'org.eclipse.swtbot:org.eclipse.swtbot.swt.finder:+'

    testImplementation 'junit:junit:4.12'
    testImplementation 'org.junit.jupiter:junit-jupiter:5.5.2'
	testRuntimeOnly    'org.junit.vintage:junit-vintage-engine:5.5.2'
}

test {
	useJUnitPlatform {
	}
	testLogging {
		events("passed", "skipped", "failed")
	}
}
````
The previous complaints are gone with the slicing option.

Now it tells me, it cannot resolve the deps:
````
Could not resolve: org.eclipse.swtbot:org.eclipse.swtbot.go
Could not resolve: org.eclipse.swtbot:org.eclipse.swtbot.junit4_x:+
Could not resolve: org.eclipse.swtbot:org.eclipse.swtbot.swt.finder:+
````

Frank

**Comment by frankbenoit** [comment]
Hi

now i learned, that dots in the groupId are not good, as they are seen as subdirs and p2asmaven does not do those.
I changed `org.eclipse.swtbot` to be `swtbot` only.

````
Execution failed for task ':compileJava'.
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not find any matches for swtbot:org.eclipse.swtbot.go:+ as no versions of swtbot:org.eclipse.swtbot.go are available.
     Searched in the following locations:
       - https://jcenter.bintray.com/swtbot/org.eclipse.swtbot.go/maven-metadata.xml
       - https://repo.maven.apache.org/maven2/swtbot/org.eclipse.swtbot.go/maven-metadata.xml
       - file:/C:/prj/build/p2asmaven/maven/swtbot/org.eclipse.swtbot.go/maven-metadata.xml
       - file:/C:/prj/build/p2asmaven/maven/swtbot/org.eclipse.swtbot.go/2.8.0.201906121535/org.eclipse.swtbot.go-2.8.0.201906121535.pom
````

But the file `c:\prj\build\p2asmaven\maven\swtbot\org.eclipse.swtbot.go\maven-metadata.xml` is existing and lists the available version.

What else can i check?

Frank

**Comment by nedtwigg** [comment]
Are you using Gradle 6?  There is a [known bug](https://github.com/diffplug/goomph/issues/106) with Gradle 6 and p2asmaven.

**Comment by frankbenoit** [comment]
Hi

yes, that's finally it.
Back to 5.6.2 made it work.

Thanks!

Frank

**Comment by liblit** [comment]
@frankbenoit, that “known bug” now has [a suggested fix](https://github.com/diffplug/goomph/issues/106#issuecomment-561945606) if you prefer to move back to Gradle 6.

**Comment by frankbenoit** [comment]
@liblit 
Thanks for hint.

I tried to get this work:

````
repositories {
    jcenter()
	mavenCentral()
	maven {
            repo 'http://download.eclipse.org/technology/swtbot/releases/latest'
	    metadataSources {
	        mavenPom()
	        artifact()
	    }
	}
}

p2AsMaven {
    group 'swtbot', {
        repo 'http://download.eclipse.org/technology/swtbot/releases/latest'
        iu 'org.eclipse.swtbot.go'
        iu 'org.eclipse.swtbot.junit4_x'
        iu 'org.eclipse.swtbot.swt.finder'
        iu 'org.apache.log4j'
        slicingOption 'followStrict', 'true'
    }
}
````

But this gives:
````
* What went wrong:
You must specify a URL for a Maven repository.
````

Any idea how to apply the workaround using p2AsMaven?

Frank

**Comment by liblit** [comment]
@frankbenoit asked:
> Any idea how to apply the workaround using p2AsMaven?

I was able to [stop using `p2AsMaven` entirely](https://github.com/wala/WALA/pull/587). Unfortunately that means I have not used [the suggested fix](https://github.com/diffplug/goomph/issues/106#issuecomment-561945606) myself, so I have nothing more to suggest.

**Comment by nedtwigg** [comment]
I think it will require `goomph` to implement the workaround, which I plan to do soon.  Watch #106 for status updates.

**Comment by frankbenoit** [comment]
@nedtwigg 

I tried locally, adding in AsMavenPlugin line 194:
````
				maven.metadataSources( sources -> {
					sources.mavenPom();
					sources.artifact();
				});

````
makes it work with Gradle 6.
