### ISSUE TITLE
Credentials

### ISSUE THREAD

**Issue by dhakehurst** [diffplug/goomph#123]
Hi,
love it.

am trying to use the com.diffplug.p2.asmaven plugin, but how do I set the credentials of the p2 repository I am downloading from

**Comment by nedtwigg** [comment]
We've got docs on how to [setup a proxy credentials here](https://javadoc.io/static/com.diffplug.gradle/goomph/3.22.0/com/diffplug/gradle/p2/AsMavenPlugin.html#proxy-support).  For other kinds of credentials, you'll probably need to dig in to eclipse's docs on the [`p2.ant` task](https://wiki.eclipse.org/Equinox/p2/Ant_Tasks), since we're pretty much just [shelling out to it](https://github.com/diffplug/goomph/blob/1b09ca0cc814f074e7421eb1174758616a4461ab/src/main/java/com/diffplug/gradle/p2/P2Model.java#L250-L275).
