### ISSUE TITLE
Eclipse stopped actively enhancing PDE Build from version 4.18, Will this plugin work even for versions newer than 4.18

### ISSUE THREAD

**Issue by zeefahs13** [diffplug/goomph#160]

**Comment by nedtwigg** [comment]
At DiffPlug, we use [`eclipseMavenCentral`](https://javadoc.io/doc/com.diffplug.gradle/goomph/latest/com/diffplug/gradle/eclipse/MavenCentralPlugin.html) and nothing else. We will always keep the `eclipseMavenCentral` plugin up-to-date, because we need it. For the rest, it's known working up to `4.15.0` and then we stopped needing it. Happy to take PRs to fix it or add functionality, happy to host issues where people are tracking which things are working and which aren't. But we aren't working on it ourselves.

**Comment by zeefahs13** [comment]
Thank you @nedtwigg . One last question

Is there is any documentation on usage of goomph? Like a wiki or any pdf apart from javadoc?

**Comment by nedtwigg** [comment]
- a few blog posts and a talk: https://github.com/diffplug/goomph#blog-posts
- an example project: https://github.com/diffplug/gradle-and-eclipse-rcp
