### ISSUE TITLE
Can goomph be used with E(fx)clipse?

### ISSUE THREAD

**Issue by MarceloRuiz** [diffplug/goomph#31]
Hi,

I was researching about using Gradle to build Eclipse RCP applications and found the video about Goomph during the Gradle Summit 2016.

I need to write a pure JavaFX RCP application and I was thinking of using e(fx)clipse as the platform. I was wondering if Goomph could help with this task. I know the guys at e(fx)clipse created a maven repository with all the dependencies for e(fx)clipse, but I don't know if that is relevant for this case. Also, during the video presentation I got the impression that Goomph takes the configuration from Eclipse to create the Gradle project. Is the reverse also possible? If I have a Gradle build script with subprojects, will Goomph convert it into a RCP Eclipse application with one module per subproject?

Thanks!

**Comment by nedtwigg** [comment]
Goomph isn't a monolith - it's a collection of a-la carte pieces.

One of its pieces, [`com.diffplug.gradle.p2.asmaven`](https://diffplug.github.io/goomph/javadoc/3.7.2/com/diffplug/gradle/p2/AsMavenPlugin.html), takes a p2 repository and turns it into a maven repository.  Since e(fx)clipse already has a maven repository, you don't need that part - just use the maven repo published by e(fx)clipse.

> I got the impression that Goomph takes the configuration from Eclipse to create the Gradle project.

Eclipse PDE uses the `build.properties` file to specify code, assets, etc.  [`com.diffplug.gradle.eclipse.buildproperties`](https://diffplug.github.io/goomph/javadoc/3.7.2/com/diffplug/gradle/eclipse/BuildPropertiesPlugin.html) lets you use that file to also setup a gradle project.  If you already have a gradle project setup, then just don't apply that plugin.

You will need to generate OSGi manifests.  Many eclipse projects do this manually.  Instead, I would recommend using [`com.diffplug.gradle.osgi.bndmanifest`](https://diffplug.github.io/goomph/javadoc/3.7.2/com/diffplug/gradle/osgi/BndManifestPlugin.html).

> If I have a Gradle build script with subprojects, will Goomph convert it into a RCP Eclipse application with one module per subproject?

You have to build OSGi bundles, and then you have to combine them into an RCP application.  Goomph has plugins for building the bundles, and it has plugins for building the RCP application.

Tinker with this example.  It does all the things you need.  Depending on how your project is setup, you can omit some of the plugins that this example uses.  Because goomph is a-la-carte instead of a monolith, you can just use the pieces you need and ignore the rest.
https://github.com/diffplug/gradle-and-eclipse-rcp

**Comment by MarceloRuiz** [comment]
Hi Ned, thanks for the answer. I have been trying to make a simple example run but I got into a problem I am having trouble solving, and maybe you can give me a hint on how to approach it.

Looking at the sample maven application for e(fx)clispse and its launcher:

[https://github.com/BestSolution-at/e4-efxclipse-maven-sample](efxclipse-maven-sample)
[https://github.com/BestSolution-at/maven-e4-launcher](maven-e4-launcher)

I noticed the launcher takes the location of an elc file as an argument. That elc file points to the plugins the application needs, which I provided as runtime dependencies in my gradle.build file. The launcher also creates a _config.ini_ and a _bundles.info_ file in a temp folder and passes that information as a configuration argument to an instance of _org.eclipse.equinox.launcher.Main_. Is all that parsing and custom configuration files creation necessary? I did not notice anything like that in your example. 

At this point, I just created a simple Launcher class that implements _IApplication_  that has a _main_ method that calls _org.eclipse.equinox.launcher.Main_ with empty arguments. I was expecting the _start_ method to be called, but I get an exception stating the osgi framework is not found.

Thanks!

**Comment by nedtwigg** [comment]
ELC looks like an e(fx)clipse-specific file, I don't know anything about it.  An eclipse application is defined as such:

The application is this file, and has to implement `org.eclipse.equinox.app.IApplication`.
https://github.com/diffplug/gradle-and-eclipse-rcp/blob/master/com.diffplug.rcpdemo/src/com/diffplug/rcpdemo/Application.java

`start()` is called on startup, and `stop()` on shutdown.

It is registered with the eclipse runtime by the `plugin.xml` file:
https://github.com/diffplug/gradle-and-eclipse-rcp/blob/8ddebc3ce221557b1066de31521035db2e2a2c60/com.diffplug.rcpdemo/plugin.xml#L5-L15

The native launcher picks it using the `application` property in this file:
https://github.com/diffplug/gradle-and-eclipse-rcp/blob/8ddebc3ce221557b1066de31521035db2e2a2c60/com.diffplug.rcpdemo/rcpdemo.product#L4

**Comment by MarceloRuiz** [comment]
Thanks for the answer and patience. I will keep playing with both projects and see if I can make the e(fx)clipse one work.

One more question: Are _plugin.xml_ and _rcpdemo.product_ generated through the gradle build script or are those generated by hand? I noticed the plugins section has references to the subprojects. Do I need to keep them up-to-date by hand (if I add a new subproject for example) or are they updated automatically by the gradle build?

Thanks again!

**Comment by nedtwigg** [comment]
plugin.xml and rcpdemo.product are both generated by hand.  Eclipse has tooling to help with both. 
 MANIFEST.MF can be autogenerated by Goomph (the bndmanifest plugin).
