### ISSUE TITLE
[BuildPropertiesPlugin] Java src/main/resources convention conflict

### ISSUE THREAD

**Issue by hacki11** [diffplug/goomph#45]
Having a module with java convention (src/main/java and src/main/resources) instead of eclipse mixed src/ directory conflicts and causes too much output in wrong folders.

Example: log4j.properties inside src/main/resources
build.properties contains: src/main/resources

Result:
![image](https://user-images.githubusercontent.com/15319906/34080538-f2c61458-e33f-11e7-89a8-c4f7f8e9e6d6.png)

The duplicate main is caused by the copy of src/**:
https://github.com/diffplug/goomph/blob/a2dbf4c2d03559649fc776694dc523944d8010a1/src/main/java/com/diffplug/gradle/eclipse/BuildPropertiesPlugin.java#L90

The duplicate folder structure of resources/main/src/main/resources is caused by including the resource path to it's root instead of using just the contents from src/main/resources
https://github.com/diffplug/goomph/blob/a2dbf4c2d03559649fc776694dc523944d8010a1/src/main/java/com/diffplug/gradle/eclipse/BuildPropertiesPlugin.java#L83

Expected result:
![image](https://user-images.githubusercontent.com/15319906/34080556-5c41358e-e340-11e7-9c6c-c552f246a94a.png)

**Comment by nedtwigg** [comment]
Hmmm...  The reason for the current behavior is that it is common for Eclipse plugins to have `.properties` and image files strewn around the source folders.  Without this: https://github.com/diffplug/goomph/blob/a2dbf4c2d03559649fc776694dc523944d8010a1/src/main/java/com/diffplug/gradle/eclipse/BuildPropertiesPlugin.java#L90-L92 all of these resource files would be missing.

It seems there's a conflict here between a plugin for

1. easy migration of legacy plugins with the standard eclipse layout (current behavior)
2. the new maven/gradle canonical way

But since 2 is just what Gradle does out of the box, I'm not sure why you're using the buildproperties plugin at all?

I'm not sure if all of the Eclipse build tools support the maven/gradle canonical way.  For example, the PdeBuildTask needs the path to the [*source* folder that holds the .product file](https://github.com/diffplug/gradle-and-eclipse-rcp/blob/5e80b68bfc04bbda9b1598c6ceb220fa043d5dc7/deploy/build.gradle#L25).  I believe when it compiles, the eclipse tooling will put `.properties` files in the source folder into the compiled jar, but Gradle and Maven will not (without the line in the BuildProperties plugin that is causing you trouble right now).

**Comment by hacki11** [comment]
i disabled the plugin completely - seems to not break anything
