### ISSUE TITLE
org.eclipse.equinix.ds no more part of Eclipse

### ISSUE THREAD

**Issue by frankbenoit** [diffplug/goomph#98]
Hi Ned,

With Eclipse 4.10 the plugin org.eclipse.equinix.ds was removed from the platform.
See https://help.eclipse.org/2018-12/index.jsp?topic=%2Forg.eclipse.platform.doc.isv%2Fporting%2F4.10%2Frecommended.html&cp=2_3_1_3&anchor=EquinoxDS_to_FelixSCR

It is referenced here:
https://github.com/diffplug/goomph/blob/6330cd132f1b0670064d7fac15c3f377caf5e867/src/main/java/com/diffplug/gradle/eclipserunner/EquinoxLauncher.java#L96

Frank

**Comment by nedtwigg** [comment]
Great find, thanks!  Now we need to require one of `org.eclipse.equinox.ds` or `org.apache.felix.scr`, correct?

Sounds like this won't cause breakage right away:

> keep it for some time available in our update site to avoid breaking clients who strongly need this one

but will soon, so we should make this change before too long.  I'm happy to accept a PR for this, or I'll get to it myself in a week or two.

**Comment by nedtwigg** [comment]
In #137, we adapted to Java 11 and the post-`equinox.ds` world. In #145, we added a little hack so that the old `equinox.ds` stuff could still work because I can't get `p2asmaven` to work without it. So we should now have all the pieces of this floating around, although the exact combination of eclipse props + JRE version is a bit tricky to figure out.
